/** US States + DC for dropdowns */
export const US_STATES = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "District of Columbia",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
] as const;

export const STRUCTURE_TYPES = [
  "Guyed",
  "Monopole",
  "Other",
  "Rooftop",
  "Self Support",
  "unclassified",
] as const;

export const PROVIDER_RESIDENT_OPTIONS = ["Yes", "No"] as const;

export const IMPORT_TEMPLATE_HEADERS = [
  "SITE ID",
  "SITE NAME",
  "AREA NAME",
  "DISTRICT NAME",
  "PROVIDER",
  "PROVIDER RESIDENT",
  "ADDRESS",
  "CITY",
  "COUNTY",
  "STATE",
  "ZIP CODE",
  "CMA ID",
  "CMA NAME",
  "STRUCTURE TYPE",
  "SITE TYPE",
  "GE",
  "STRUCTURE HEIGHT",
  "LATITUDE",
  "LONGITUDE",
  "SITE ALT ID",
] as const;

export type StructureType = (typeof STRUCTURE_TYPES)[number];
export type ProviderResidentOption = (typeof PROVIDER_RESIDENT_OPTIONS)[number];
