/**
 * RBAC permission constants. Enforce on APIs and UI.
 */
export const PERMISSIONS = {
  SITES_READ: "sites:read",
  SITES_WRITE: "sites:write",
  SITES_DELETE: "sites:delete",
  SITES_EXPORT: "sites:export",
  IMPORT_RUN: "import:run",
  IMPORT_TEMPLATE_DOWNLOAD: "import:template:download",
  USERS_READ: "users:read",
  USERS_MANAGE: "users:manage",
  ROLES_READ: "roles:read",
  ROLES_MANAGE: "roles:manage",
  AUDIT_READ: "audit:read",
  BACKUPS_MANAGE: "backups:manage",
  PROJECTS_READ: "projects:read",
  PROJECTS_MANAGE: "projects:manage",
  PROJECTS_EXPORT: "projects:export",
  LEASES_READ: "leases:read",
  LEASES_WRITE: "leases:write",
  LEASES_DELETE: "leases:delete",
  REVENUE_READ: "revenue:read",
  DOCUMENTS_READ: "documents:read",
  DOCUMENTS_WRITE: "documents:write",
  DOCUMENTS_DELETE: "documents:delete",
  INSIGHTS_READ: "insights:read",
  VIEWS_MANAGE: "views:manage",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

/** Role names (for seed and checks) */
export const ROLE_NAMES = {
  SUPER_ADMIN: "Super Admin",
  ADMIN: "Admin",
  DATA_MANAGER: "Data Manager",
  VIEWER: "Viewer",
} as const;

/** Role -> permissions mapping for seed */
export const ROLE_PERMISSIONS: Record<string, Permission[]> = {
  [ROLE_NAMES.SUPER_ADMIN]: [...ALL_PERMISSIONS],
  [ROLE_NAMES.ADMIN]: [
    PERMISSIONS.SITES_READ,
    PERMISSIONS.SITES_WRITE,
    PERMISSIONS.SITES_DELETE,
    PERMISSIONS.SITES_EXPORT,
    PERMISSIONS.IMPORT_RUN,
    PERMISSIONS.IMPORT_TEMPLATE_DOWNLOAD,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_READ,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.BACKUPS_MANAGE,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_MANAGE,
    PERMISSIONS.PROJECTS_EXPORT,
    PERMISSIONS.LEASES_READ,
    PERMISSIONS.LEASES_WRITE,
    PERMISSIONS.LEASES_DELETE,
    PERMISSIONS.REVENUE_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_WRITE,
    PERMISSIONS.DOCUMENTS_DELETE,
    PERMISSIONS.INSIGHTS_READ,
    PERMISSIONS.VIEWS_MANAGE,
  ],
  [ROLE_NAMES.DATA_MANAGER]: [
    PERMISSIONS.SITES_READ,
    PERMISSIONS.SITES_WRITE,
    PERMISSIONS.SITES_EXPORT,
    PERMISSIONS.IMPORT_RUN,
    PERMISSIONS.IMPORT_TEMPLATE_DOWNLOAD,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.PROJECTS_EXPORT,
    PERMISSIONS.LEASES_READ,
    PERMISSIONS.LEASES_WRITE,
    PERMISSIONS.REVENUE_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.DOCUMENTS_WRITE,
    PERMISSIONS.INSIGHTS_READ,
    PERMISSIONS.VIEWS_MANAGE,
  ],
  [ROLE_NAMES.VIEWER]: [
    PERMISSIONS.SITES_READ,
    PERMISSIONS.PROJECTS_READ,
    PERMISSIONS.LEASES_READ,
    PERMISSIONS.REVENUE_READ,
    PERMISSIONS.DOCUMENTS_READ,
    PERMISSIONS.INSIGHTS_READ,
  ],
};
