export const PERMISSIONS = {
  SITES_READ: "sites:read",
  SITES_WRITE: "sites:write",
  SITES_DELETE: "sites:delete",
  SITES_EXPORT: "sites:export",
  IMPORT_RUN: "import:run",
  IMPORT_TEMPLATE_DOWNLOAD: "import:template:download",
  USERS_READ: "users:read",
  USERS_MANAGE: "users:manage",
  ROLES_READ: "roles:read",
  ROLES_MANAGE: "roles:manage",
  AUDIT_READ: "audit:read",
  BACKUPS_MANAGE: "backups:manage",
  PROJECTS_READ: "projects:read",
  PROJECTS_MANAGE: "projects:manage",
  PROJECTS_EXPORT: "projects:export",
  LEASES_READ: "leases:read",
  LEASES_WRITE: "leases:write",
  LEASES_DELETE: "leases:delete",
  REVENUE_READ: "revenue:read",
  DOCUMENTS_READ: "documents:read",
  DOCUMENTS_WRITE: "documents:write",
  DOCUMENTS_DELETE: "documents:delete",
  INSIGHTS_READ: "insights:read",
  VIEWS_MANAGE: "views:manage",
} as const;
